project:
  type: website
  output-dir: docs
  
website:
  title: "Sergio de las Heras"
  favicon: favicon.ico
  navbar:
    left:
      #- href: index.qmd
      #  text: Home
      - href: about.qmd
        text: About
  page-footer: 
    left: "© 2024 Sergio de las Heras" 
    right: 
      - icon: linkedin
        href: "https://linkedin.com/in/sergiodlash"
      - icon: github
        href: "https://github.com/sergiodlash"
      - text: "{{< ai researchgate >}}"
        href: "https://www.researchgate.net/profile/Sergio-De-Las-Heras"

format:
  html:
    base-url: sergiodlash.github.io
    theme: cosmo
    css: styles.css
    toc: false
    
resources:
  - _extensions/schochastics/academicons



